name: Build all from source

on:
  #push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      cv_version:
        description: 'build all from source'
        default: '4.9.0'
        required: true
        type: string

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  OPENCV_BUILD_ROOT: D:/opencv

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8.15.3
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: run pnpm install
      run: pnpm install --frozen-lockfile

    - name: build CJS + ESM files
      run: pnpm run prepack

    - name: build native modules using node-gyp
      run: pnpm run rebuild

    - name: install deps in test
      working-directory: ./test
      run: pnpm install --frozen-lockfile

    - name: build OpenCV ${{ inputs.cv_version }}
      working-directory: ./test
      run: pnpm build-opencv --version ${{ inputs.cv_version }} rebuild

    - name: run test-appveyor test
      working-directory: ./test
      run: pnpm run test-appveyor
