name: Use openCV from Apt

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - "cc/**"
      - "install/**"
      - "lib/**"
      - "test/**"
      - "typings/**"
      - "package.json"
      - ".github/workflows/prebuild-linux.yml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "cc/**"
      - "install/**"
      - "lib/**"
      - "test/**"
      - "typings/**"
      - "package.json"
      - ".github/workflows/prebuild-linux.yml"

env:
  OPENCV4NODEJS_DISABLE_AUTOBUILD: 1

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opencv_version:
          - 4
        node_version:
          # - 16
          # - 18
          - 20

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - name: Install Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'pnpm'

    - name: Install OpenCV ${{ matrix.opencv_version }}
      run: |
        sudo apt update
        sudo apt install libopencv-dev
        
    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: 8
        run_install: |
         - recursive: false
    
    - run: pnpm install --frozen-lockfile
          
    - name: pnpm run prepack
      run: pnpm run prepack

    - name: install deps in test
      working-directory: ./test
      run: pnpm install

    - name: run test-appveyor test
      working-directory: ./test
      run: pnpm run test-appveyor
